FROM python:3.8-slim

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && \
  apt-get --no-install-recommends --assume-yes install build-essential

RUN pip install uwsgi

#RUN mkdir -p /srv
ADD ./src /srv
WORKDIR /srv

# Run the image as a non-root user
RUN adduser -D wildsearch_bot
USER wildsearch_bot

WORKDIR /